include_recipe "../../cookbooks/homebrew"

include_recipe "../../cookbooks/alacritty"
include_recipe "../../cookbooks/azdot"
include_recipe "../../cookbooks/direnv"
include_recipe "../../cookbooks/docker"
include_recipe "../../cookbooks/git"
include_recipe "../../cookbooks/gnuutils"
include_recipe "../../cookbooks/shell"
include_recipe "../../cookbooks/tmux"
include_recipe "../../cookbooks/tool"
include_recipe "../../cookbooks/firacode"
include_recipe "../../cookbooks/rustup"
include_recipe "../../cookbooks/vim"
