#!/bin/bash
set -euCo pipefail

realpath="$(realpath $0)"
dotfiles_root="$(dirname ${realpath})/.."
source "${dotfiles_root}/script/lib/script"
source "${dotfiles_root}/script/lib/config"
source "${dotfiles_root}/script/lib/tool"

script_uninstall
config_uninstall
tool_uninstall
