#!/bin/bash
set -euCo pipefail

cd "$(dirname $0)/.."
CONFIGS=${@}

stow -vD --no-folding -d . -t ./bin script
stow -vD --no-folding -d ./config -t ${HOME} ${CONFIGS}
stow -vD -d ./tool -t ./bin $(find ./tool/* -type d -exec basename {} \;)
