#!/bin/bash
set -euCo pipefail

dotfiles_root="$(dirname $0)/.."
source "${dotfiles_root}/script/lib/script"
source "${dotfiles_root}/script/lib/config"
source "${dotfiles_root}/script/lib/tool"

script_uninstall
config_uninstall
tool_uninstall
