#!/bin/bash
set -euCo pipefail

cd "$(dirname $0)/.."
CONFIGS=${@}

script/azdot-uninstall ${CONFIGS}

git pull origin "$(git branch --show-current)"
git submodule foreach git reset --hard HEAD # Discard local changes
git submodule update --init

script/azdot-install ${CONFIGS}
