#!/bin/bash

function tool_install() {
  pushd "${dotfiles_root}"
  mkdir -p ${HOME}/.local/bin
  stow -v --no-folding -d ./tool -t ${HOME}/.local/bin $(find ./tool/* -type d -exec basename {} \;)

  local binaries="$(find ${HOME}/.local/bin/* -mindepth 0 -maxdepth 0 -type l)"
  if [ -n "${binaries}" ]; then
    chmod +x $binaries
  fi
  echo "Please add '\${HOME}/.local/bin' to \$PATH"
  popd
}


function tool_uninstall() {
  pushd "${dotfiles_root}"
  stow -vD -d ./tool -t ${HOME}/.local/bin $(find ./tool/* -type d -exec basename {} \;)
  popd
}
