#!/bin/bash

function tool_install() {
  pushd "${dotfiles_root}"
  mkdir -p ./bin
  stow -v --no-folding -d ./tool -t ./bin $(find ./tool/* -type d -exec basename {} \;)

  local binaries="$(find ./bin/* -type l)"
  if [ -n "${binaries}" ]; then
    chmod +x $binaries
  fi
  echo "Please add '$(pwd)/bin' to \$PATH"
  popd
}


function tool_uninstall() {
  pushd "${dotfiles_root}"
  stow -vD -d ./tool -t ./bin $(find ./tool/* -type d -exec basename {} \;)
  popd
}
